# LoRa driver subsystem
CONFIG_LORA=y
CONFIG_GPIO=y

# Main app

CONFIG_MAIN_STACK_SIZE=2048

# Power management

CONFIG_PM=y
CONFIG_PM_DEVICE=y

# Logging / shell management

CONFIG_LOG=y
CONFIG_SHELL=n
CONFIG_CONSOLE=y
CONFIG_DEBUG=n
